### ISSUE TITLE
Division by zero error

### ISSUE THREAD

**Issue by unleashed7** [amerkurev/scrapper#8]
Any way I can get around this error to scrape a specific website?

```
2024-03-12 04:55:54 ERROR:    Exception in ASGI application
2024-03-12 04:55:54 Traceback (most recent call last):
2024-03-12 04:55:54   File "/usr/local/lib/python3.10/dist-packages/uvicorn/protocols/http/httptools_impl.py", line 426, in run_asgi
2024-03-12 04:55:54     result = await app(  # type: ignore[func-returns-value]
2024-03-12 04:55:54   File "/usr/local/lib/python3.10/dist-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
2024-03-12 04:55:54     return await self.app(scope, receive, send)
2024-03-12 04:55:54   File "/usr/local/lib/python3.10/dist-packages/fastapi/applications.py", line 1106, in __call__
2024-03-12 04:55:54     await super().__call__(scope, receive, send)
2024-03-12 04:55:54   File "/usr/local/lib/python3.10/dist-packages/starlette/applications.py", line 122, in __call__
2024-03-12 04:55:54     await self.middleware_stack(scope, receive, send)
2024-03-12 04:55:54   File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/errors.py", line 184, in __call__
2024-03-12 04:55:54     raise exc
2024-03-12 04:55:54   File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/errors.py", line 162, in __call__
2024-03-12 04:55:54     await self.app(scope, receive, _send)
2024-03-12 04:55:54   File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/exceptions.py", line 79, in __call__
2024-03-12 04:55:54     raise exc
2024-03-12 04:55:54   File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/exceptions.py", line 68, in __call__
2024-03-12 04:55:54     await self.app(scope, receive, sender)
2024-03-12 04:55:54   File "/usr/local/lib/python3.10/dist-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
2024-03-12 04:55:54     raise e
2024-03-12 04:55:54   File "/usr/local/lib/python3.10/dist-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
2024-03-12 04:55:54     await self.app(scope, receive, send)
2024-03-12 04:55:54   File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 718, in __call__
2024-03-12 04:55:54     await route.handle(scope, receive, send)
2024-03-12 04:55:54   File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 276, in handle
2024-03-12 04:55:54     await self.app(scope, receive, send)
2024-03-12 04:55:54   File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 66, in app
2024-03-12 04:55:54     response = await func(request)
2024-03-12 04:55:54   File "/usr/local/lib/python3.10/dist-packages/fastapi/routing.py", line 274, in app
2024-03-12 04:55:54     raw_response = await run_endpoint_function(
2024-03-12 04:55:54   File "/usr/local/lib/python3.10/dist-packages/fastapi/routing.py", line 191, in run_endpoint_function
2024-03-12 04:55:54     return await dependant.call(**values)
2024-03-12 04:55:54   File "/home/user/app/routers/article.py", line 129, in parse_article
2024-03-12 04:55:54     article['content'] = htmlutil.improve_content(
2024-03-12 04:55:54   File "/home/user/app/internal/util/htmlutil.py", line 37, in improve_content
2024-03-12 04:55:54     if levenshtein_similarity(text[:min_len], title[:min_len]) > 0.9:
2024-03-12 04:55:54   File "/home/user/app/internal/util/htmlutil.py", line 119, in levenshtein_similarity
2024-03-12 04:55:54     return 1 - d[-1][-1] / max(len(str1), len(str2))
2024-03-12 04:55:54 ZeroDivisionError: division by zero
2024-03-12 04:55:55 INFO:     127.0.0.1:35596 - "GET /ping HTTP/1.1" 200 OK
```

**Comment by amerkurev** [comment]
Hey @unleashed7, could you send me the page URL where the zero division error is occurring? Thanks!
